server:
  port:
    9090
spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: http://localhost:8082/order/
          predicates:
            - Path=/order/**
        - id: PRODUCT-SERVICE
          uri: http://localhost:8080/product/
          predicates:
            - Path=/product/**
        - id: PAYMENT-SERVICE
          uri: http://localhost:8086/payment/
          predicates:
            - Path=/payment/**