server:
  port: 8082

spring:
  datasource:
    url: jdbc:oracle:thin:CHAT_DB/@localhost:1521/orcl.Perso.Local
    username: CHAT_DB
    password: CHAT_DB
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none

  application:
    name:
      ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296